# Generated by Django 4.2.28 on 2026-02-28 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('stock', '0001_initial'),
        ('sale_orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquantity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_quantity', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockquantity',
            name='stock_lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_quantity', to='stock.stocklot'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_move_lines', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='stock_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_move_lines', to='stock.stocklot'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='stock_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_move_lines', to='stock.stockmove'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_move', to='purchase_orders.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='sale_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_move', to='sale_orders.saleorderline'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='products.product'),
        ),
    ]
