# Generated by Django 4.2.28 on 2026-02-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_remove_purchaseorder_notes_purchaseorder_total_price_and_more'),
        ('sale_orders', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_move', to='purchase_orders.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='sale_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_move', to='sale_orders.saleorderline'),
        ),
    ]
