# Generated by Django 4.2.28 on 2026-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockmove_purchase_order_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='origin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
