# Generated by Django 4.2.28 on 2026-02-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmove_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquantity',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
