# Generated by Django 4.2.28 on 2026-02-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_unique_product_sku_per_user'),
        ('stock', '0004_stockquantity_reserved_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockquantity',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockquantity',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_quantity', serialize=False, to='products.product'),
        ),
    ]
