@baseUrl = http://localhost:8000
@apiVersion = v1
@contentType = application/json

###

# @name HealthCheck
GET {{baseUrl}}/{{apiVersion}}/health/
Content-Type: {{contentType}}

###

# @name Signup
POST {{baseUrl}}/{{apiVersion}}/users/
Content-Type: {{contentType}}

{
    "first_name": "Test",
    "last_name": "User",
    "username": "testuser",
    "password": "testpassword"
}

###

# @name Login
POST {{baseUrl}}/{{apiVersion}}/auth/login/
Content-Type: {{contentType}}

{
    "username": "testuser",
    "password": "testpassword"
}

###

# @name Refresh
POST {{baseUrl}}/{{apiVersion}}/auth/refresh/
Content-Type: {{contentType}}

###

# @name Logout
POST {{baseUrl}}/{{apiVersion}}/auth/logout/
Content-Type: {{contentType}}

###

# @name Me
GET {{baseUrl}}/{{apiVersion}}/auth/me/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name CreateProduct
POST {{baseUrl}}/{{apiVersion}}/products/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

{
    "name": "Product 1",
    "sku": "1234567890",
    "description": "Product 1 description",
    "unit": "kg"
}

###

# @name ListProducts
GET {{baseUrl}}/{{apiVersion}}/products/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetProduct
GET {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetProductStockQuantity
GET {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/stock-quantity/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetProductMoves
GET {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/moves/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetProductLots
GET {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/lots/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetProductFinancialData
GET {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/financial-data/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name UpdateProduct
PATCH {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

{
    "name": "Product 1 Updated"
}

###

# @name DeleteProduct
DELETE {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name UpdateProductQuantity
PATCH {{baseUrl}}/{{apiVersion}}/products/{{CreateProduct.response.body.$.id}}/update-quantity/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

[
    {
        "stock_lot_id": 25,
        "quantity": 400,
        "create_new_lot": false
    },
    {
        "create_new_lot": true,
        "quantity": 200,
        "unit_price": 100
    }
]

###

# @name CreatePurchaseOrder
POST {{baseUrl}}/{{apiVersion}}/purchase-orders/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

{
    "supplier_name": "Supplier 1",
    "lines": [
        {
            "product": "{{CreateProduct.response.body.$.id}}",
            "quantity": 10,
            "unit_price": 100
        }
    ]
}

###

# @name ListPurchaseOrders
GET {{baseUrl}}/{{apiVersion}}/purchase-orders/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetPurchaseOrder
GET {{baseUrl}}/{{apiVersion}}/purchase-orders/{{CreatePurchaseOrder.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name UpdatePurchaseOrder
PATCH {{baseUrl}}/{{apiVersion}}/purchase-orders/{{CreatePurchaseOrder.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

{
    "lines": [
        {
            "product": "{{CreateProduct.response.body.$.id}}",
            "quantity": 20,
            "unit_price": 100
        }
    ]
}

###

# @name DeletePurchaseOrder
DELETE {{baseUrl}}/{{apiVersion}}/purchase-orders/{{CreatePurchaseOrder.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name ConfirmPurchaseOrder
PATCH {{baseUrl}}/{{apiVersion}}/purchase-orders/{{CreatePurchaseOrder.response.body.$.id}}/confirm/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name ReceivePurchaseOrder
PATCH {{baseUrl}}/{{apiVersion}}/purchase-orders/{{CreatePurchaseOrder.response.body.$.id}}/receive/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name CreateSaleOrder
POST {{baseUrl}}/{{apiVersion}}/sale-orders/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

{
    "customer_name": "Customer 1",
    "lines": [
        {
            "product": "{{CreateProduct.response.body.$.id}}",
            "quantity": 10,
            "unit_price": 100
        }
    ]
}

###

# @name ListSaleOrders
GET {{baseUrl}}/{{apiVersion}}/sale-orders/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name GetSaleOrder
GET {{baseUrl}}/{{apiVersion}}/sale-orders/{{CreateSaleOrder.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name UpdateSaleOrder
PATCH {{baseUrl}}/{{apiVersion}}/sale-orders/{{CreateSaleOrder.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

{
    "lines": [
        {
            "product": "{{CreateProduct.response.body.$.id}}",
            "quantity": 20,
            "unit_price": 100
        }
    ]
}

###

# @name DeleteSaleOrder
DELETE {{baseUrl}}/{{apiVersion}}/sale-orders/{{CreateSaleOrder.response.body.$.id}}/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name ConfirmSaleOrder
PATCH {{baseUrl}}/{{apiVersion}}/sale-orders/{{CreateSaleOrder.response.body.$.id}}/confirm/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name ReserveSaleOrder
PATCH {{baseUrl}}/{{apiVersion}}/sale-orders/{{CreateSaleOrder.response.body.$.id}}/reserve/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###

# @name DeliverSaleOrder
PATCH {{baseUrl}}/{{apiVersion}}/sale-orders/{{CreateSaleOrder.response.body.$.id}}/deliver/
Content-Type: {{contentType}}
Authorization: Bearer {{Refresh.response.body.$.access}}

###