# Generated by Django 4.2.28 on 2026-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('created_by', 'sku'), name='unique_product_sku_per_user'),
        ),
    ]
